name: Build and Attach Engine File Assets

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:    
  build_nlp_engine:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]  # Run on both latest and Ubuntu 22.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensure submodules are updated

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build cmake g++ git curl zip unzip tar pkg-config python3

      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git /vcpkg
          cd /vcpkg
          ./bootstrap-vcpkg.sh
          
      - name: Install Dependencies with vcpkg
        run: |
          cd /vcpkg
          ./vcpkg install --triplet x64-linux

      - name: Build NLP Engine
        run: |
          mkdir -p build
          cmake -DCMAKE_BUILD_TYPE=Release -B build -S . -DCMAKE_TOOLCHAIN_FILE="/vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake --build build/ --target all

      - name: Test Executable
        run: ./bin/nlp --version || true

      - name: Zip Engine Files
        uses: papeloto/action-zip@v1
        with:
          files: bin/
          recursive: true
          dest: nlpengine.zip
          
      - name: Upload Engine Zip
        uses: actions/upload-artifact@v4
        with:
          name: nlpengine.zip
          path: ${{ github.workspace }}/nlpengine.zip